@startuml
skinparam classBorderColor #4F4F4F
skinparam classBackgroundColor #FFFFFD

class Plateau{
    - board : Piece[][]
    + whitePiecesList : Piece[]
    + blackPiecesList : Piece[]
    

    + Plateau()
    + getBoard() : Piece[][]
    + getWhitePL() : Piece[]
    + getBlackPL() : Piece[]
    + upgradePiece(pos : Position, piece : Piece) : Piece

}

@enduml